### ISSUE TITLE
Fix for potential Access Violation

### ISSUE THREAD

**Issue by DelphiGit** [TurboPack/Orpheus#10]
Hi,
Don't know if you've seen it, but I added a pull request for fixing a potential AV in "ovcfiler.pas". I know it's potential cause it happened to me when using a TOvcIniFileStore component. :smile: 
Just thought I'd mention it, since the proper way to do things is probably to post an issue first...

Have a wonderful weekend!

**Comment by romankassebaum** [comment]
Fixed.
