### ISSUE TITLE
TOvcFormState: Apps don't start when closed minimized

### ISSUE THREAD

**Issue by LeonardGC** [TurboPack/Orpheus#11]
When you use TOvcFormState, and an application is closed when it's minimized, it won't start anymore.
To solve it, you need to change the following line (line 609):
Orig:
procedure TOvcFormState.ReadFormState(Form : TWinControl; const Section : string);
...
      case ShowCmd of
        SW_SHOWNORMAL, SW_RESTORE, SW_SHOW : WinState := wsNormal;
        SW_MINIMIZE, SW_SHOWMINIMIZED      : WinState := wsMinimized;
        SW_MAXIMIZE                        : WinState := wsMaximized;
      else
        WinState := wsNormal;
      end;
      if (WinState = wsMinimized) and (Form = Application.MainForm) then begin   // <<<
        PostMessage(Application.Handle, WM_SYSCOMMAND, SC_MINIMIZE, 0);
        Exit;
      end;
      WindowState := WinState;
    end;

Fix:
      case ShowCmd of
        SW_SHOWNORMAL, SW_RESTORE, SW_SHOW : WinState := wsNormal;
        SW_MINIMIZE, SW_SHOWMINIMIZED      : WinState := wsMinimized;
        SW_MAXIMIZE                        : WinState := wsMaximized;
      else
        WinState := wsNormal;
      end;
      if (WinState = wsMinimized) and (not Assigned(Application.MainForm)) then begin  //<<< Fix
        PostMessage(Application.Handle, WM_SYSCOMMAND, SC_MINIMIZE, 0);
        Exit;
      end;
      WindowState := WinState;
    end;

**Comment by romankassebaum** [comment]
Fixed.
