### ISSUE TITLE
Cannot install Orpheus in Delphi XE2

### ISSUE THREAD

**Issue by tvbh** [TurboPack/Orpheus#12]
I succeded to install Orpheus408.2 in Delphi XE5, but I also need to install it in XE2. That fails. 
O408_r160.bpl compiles, and so do O408_d160.bpl, but when I try to in stall the latter, I get a message:
It was not possible to start the program as O408_r160.bpl is missing on the computer. You can try to fix the problem by re-installing the program.

I have also tried with older Orpheus versions I have and with the one on GitHub (Orpheus-master) but nothing works.

I am very grateful if someone can help me with this problem
Bengt

**Comment by romankassebaum** [comment]
You have to rename all packages and then you must fix the requires clause.
