### ISSUE TITLE
Cannot install in RAD Studio 10.2.1

### ISSUE THREAD

**Issue by oschubert** [TurboPack/Orpheus#13]
I was able to install Orpheus using the GetIt Manager.  Since I need to fix some bugs in Orpheus, I want to install Orpheus using the version from GitHub, but haven't been able to do so.  

I added the necessary paths as outlined in the Readme.txt 
(except, I added 
d:\orpheus\source\hpp\Win32\Debug 
instead of 
d:\orpheus\source\hpp\Win32\Develop 
as that path doesn't exist in the download).

When trying to compile OrpheusCD.bpl, I get multiple errors referencing various lines of code:
[DCC Error] ovcrptvw.pas(5646): E2023 Function needs result type
[DCC Error] ovcrptvw.pas(5646): E2029 Declaration expected but '.' found
[DCC Error] ovcrptvw.pas(5681): E2070 Unknown directive: 'TOvcCustomReportView'

The compile eventually stops with error:
[DCC Fatal Error] ovcrptvw.pas(6008): E2226 Compilation terminated; too many errors

BTW: I am only using the Builder C++ flavor in RAD Studio.

Any ideas how to get this to compile?

Oliver

![image](https://user-images.githubusercontent.com/22156863/31566208-6d45f1a8-b01e-11e7-9731-dc723b845e24.png)

**Comment by romankassebaum** [comment]
You should use the Tokyo version under https://github.com/TurboPack-Tokyo/Orpheus/.
