### ISSUE TITLE
Cannot install Orpheus in C++ Builder 10.3

### ISSUE THREAD

**Issue by oschubert** [TurboPack/Orpheus#14]
I understand that this release is for 10.2.3.  Is there an estimated date for availability for 10.3?  Currently I get the following error when trying to install it under 10.3:
[DCC Fatal Error] OvcRvExpDef.pas(2185): F2084 Internal Error: C15211

**Comment by rpottsoh** [comment]
I presume a 10.3 compatible version will be available here at some point.  I have a 10.3 compatible version available that you are welcome to use in the interim.  It is not a fork of Orpheus from TurboPack.  It was originally a mirror from https://svn.code.sf.net/p/tporpheus/code/trunk and appears to have been very well maintained over the years.  making it 10.3 compatible was not too difficult.

**Comment by oschubert** [comment]
If you can make the 10.3 compatible version available it would be very much appreciated as Orpheus was removed from the GetIt Manager in C++ Builder 10.3 and I still use numerous components of it in my application.

**Comment by oschubert** [comment]
I am not that familiar with Github, so I didn't think of looking at your repository.  Now, I did download Orpheus from there, but I can only find a package for Delphi 10.3, but not for Builder C++ 10.3.  Am I missing something here?

**Comment by rpottsoh** [comment]
Ah..  I don't use Builder.  My suggestion would be to start with the latest Builder package and then save as a 10.3 version, change the name of the packages appropriately, then try building the packages.   Then address the issues as they are pointed out by the compiler.  This is essentially what I did for Delphi.  If you need further assistance while using my fork you may want to open an issue there.  I  can try to help as much as I can, but I don't have Builder installed to work with.

Sent from my android device.

**Comment by oschubert** [comment]
I was able to compile the Orpheus package by just changing the last occurrence as described in #16.  I didn't even have to change the first occurrence.

However, when I try to install the package I get a "Entry point not found" error message.

**Comment by oschubert** [comment]
Still had to make the same change manually as in #16 for it to compile, but unfortunately I am still getting the same "Entry point not found" error as before.

**Comment by rpottsoh** [comment]
@jimmckeeth is there anything you can think of for @oschubert to try?

**Comment by jimmckeeth** [comment]
I just pushed a new update for Rio.

**Comment by flydev-fr** [comment]
@jimmckeeth I tried to compile it on Delphi Rio 10.3 Pro, it produce the same error `[DCC Fatal Error] OvcRvExpDef.pas(2185): F2084 Internal Error: C15211` and it look like the fix isn't commited in the last update.

The change needed in [OvcRvExpDef.pas#L2183](https://github.com/TurboPack/Orpheus/blob/master/source/OvcRvExpDef.pas#L2183) :
```pascal
Result := VarIsNull(TestValue) xor UnaryNot;
```
to

```pascal
Result := (TestValue = null) xor UnaryNot;
```

thanks for the update!

**Comment by rpottsoh** [comment]
This line:
https://github.com/TurboPack/Orpheus/blob/0dcfb600348b42aac37af428e51362415443ec79/source/OvcRvExpDef.pas#L2170
is also an issue.

I never did really figure out why (I would like to know).  I know `(TestValue = null) xor UnaryNot` is satisfactory to the compiler, but I do not know if it has the same desired result as the original statement that that contains `VarIsNull`.  I am not sure if the DUnit tests cover this section of code.

**Comment by oschubert** [comment]
I was able to install Orpheus using the GetIt manager (despite some error messages during the whole process).
