### ISSUE TITLE
ReportView doesn't print all pages

### ISSUE THREAD

**Issue by oschubert** [TurboPack/Orpheus#15]
In file ovcrptvw.pas changing function CalcHPages as follows fixes this problem

begin
Result := 0;
LinesLeft := 0;
{DoneSectionHeader := False; oliver11111 2010/04/20}
{DoneSectionFooter := False; oliver11111 2010/04/20}
for j := 0 to pred(Lines) do
if not SelectedOnly or IsSelected[j] then begin
while LinesLeft <= 0 do begin
DoneSectionHeader := False; {oliver11111 2010/04/20}
DoneSectionFooter := False; {oliver11111 2010/04/20}
inc(LinesLeft, (LinesPerPage - PrinterProperties.PrintHeaderLines - PrinterProperties.PrintFooterLines));
inc(Result);
end;

The original code is counting the header lines only once per report instead of counting them for every page.

**Comment by oschubert** [comment]
Looks like this bug fix still didn't make it into the current release of Orpheus.

**Comment by rpottsoh** [comment]
Submit a PR

**Comment by oschubert** [comment]
Did my first PR - hope I did everything correctly ;-).
