### ISSUE TITLE
Cannot install in Delphi 10.3.1 Pro

### ISSUE THREAD

**Issue by JacalarRick** [TurboPack/Orpheus#21]
Went to install the new Orpheus for VCL 4.1 into Rio (10.3.1).  The installation fails with an error compiling for 32 bit
![image](https://user-images.githubusercontent.com/48159175/53684692-51328500-3cc5-11e9-9691-40ac14d30b4c.png)

**Comment by romankassebaum** [comment]
I only have 10.4.2 installed.
