### ISSUE TITLE
Exception with keyboard operation. Cursor

### ISSUE THREAD

**Issue by jBitHub** [TurboPack/Orpheus#23]
**Code:**

```
procedure TImageListFo.btn21Click(Sender: TObject);
var it,itP: TO32InspectorItem;
    oig: TO32InspectorGrid;
begin
    oig := oinspctrgrd1;
    oig.ItemCollection.Clear;

    itP := oig.Add(itParent,nil);
    it := oig.Add(itString,itP);
    it.Caption := 'Prop1';
    it.DisplayText := 'Val1';
    it := oig.Add(itString,itP);
    it.Caption := 'Prop2';
    it.DisplayText := 'Val2';
end;
```
**Problem:**
If you move the cursor from a child node to a parent node, there is an exception.

Tested by FastMM4.

---------------------------
Benachrichtigung über Debugger-Exception
---------------------------
Im Projekt Program.exe ist eine Exception der Klasse $C0000005 mit der Meldung 'Zugriffsverletzung bei 0x006780d4: Lesen von Adresse 0x808080c0' aufgetreten.

**Comment by romankassebaum** [comment]
I cannot reproduce the issue without a test project.
