### ISSUE TITLE
TOvcTCPictureField pftDate issue in Sydney

### ISSUE THREAD

**Issue by YukonPete** [TurboPack/Orpheus#25]
When selecting pftDate datatype the RangeHi and RangeLo := //////////  When I attempt to enter a correct RangeHi or Lo it reverts back to the forward slashes.
The picture mask is set to mm/dd/yyyy.  Dates in the TOvcTable are displayed incorrectly and will not accept a properly entered date in the table.
Thank you,
Lee

**Comment by jcbannon** [comment]
I'm having a similar problem. Formatting of pftDate recognizes 'yyyy' but not 'mm' or 'dd'

**Comment by jcbannon** [comment]
It's not correctly reading the format fields (Picture).

**Comment by YukonPete** [comment]
jcBannon;  Were you able to correct the issue?  If so, could you please leave a fix?
Thanks

**Comment by jcbannon** [comment]
Nope. When I opened Sydney today, I was excited to see an update to Orpheus, but it didn't fix the issue. 

It's not just TOvcTCPictureField, but TOvcPictureField as well.  I'm pretty sure the problem is in OvcIntlSup where it parses the Picture, and it seems to be a Unicode incompatibility issue.

> jcBannon; Were you able to correct the issue? If so, could you please leave a fix?
> Thanks

**Comment by romankassebaum** [comment]
I need a test project.
