### ISSUE TITLE
Can't install on 10.3 C++ Builter

### ISSUE THREAD

**Issue by diegolr62** [TurboPack/Orpheus#26]
The problem is with OrpheusDBCR260, does not link
![imagen](https://user-images.githubusercontent.com/64618045/90824057-69082980-e2fc-11ea-9fc3-fdd6d5a5f5a4.png)

**Comment by YukonPete** [comment]
So what is the fix?

Sincerely,
Lee Mc Cauley
www.goprofitsource.com
715-536-7159

------ Original Message ------

**Comment by YukonPete** [comment]
By the way, I am installing it for Delphi not C++ Builder.

Sincerely,
Lee Mc Cauley
www.goprofitsource.com
715-536-7159

------ Original Message ------

**Comment by YukonPete** [comment]
Please forgive me.  You were commenting on a different issue than mine.

Sorry,
Lee

------ Original Message ------

**Comment by romankassebaum** [comment]
I only have 10.4.2.
