### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by vernonOber** [TurboPack/Orpheus#27]
Hi,
Would the maintainers of the Orpheus project consider a licensing change from Mozilla 1.1 to
Mozilla 2.0 ?

Thank-you !
- Vernon Oberholzer

**Comment by marcocantu** [comment]
Is there a specific reason for the request? Or just to have a more modern version? The issue here is the code was "inherited" by this project from an MPL 1.1. project and we'd have to make sure there is no legal obstacle in moving up to 2.0

**Comment by vernonOber** [comment]
Hi Marco,
Thank-you for the quick response.
I would like to have the Orpheus package as a dependency in a GPL licensed
project, but in my
understanding, the Mozilla 1.1 license is not compatible with the GPL, but
Mozilla 2.0 is.

Kind regards,
-Vernon Oberholzer
