### ISSUE TITLE
Can't install Orpheus from GetIt on Delphi 10.4

### ISSUE THREAD

**Issue by flydev-fr** [TurboPack/Orpheus#28]
Hi,

When I try to install Orpheus from GetIt, it fail complaining about `OrpheusDR` :

```
[dcc32 Fatal Error] OrpheusDD.dpk(61): E2202 'Package 'OrpheusDR' required not found
```

I attached a screencast of the install process: [GetIt-Orpheus Screencast](https://user-images.githubusercontent.com/11658616/127735583-de3a7887-1fc7-421a-b2fd-739bcb3b98c9.gif)

My IDE version is `Delphi 10.4 Version 27.0.40680.4203` with `Delphi 10.4 Update 2`

**Comment by romankassebaum** [comment]
I do not maintain GetIt. I can only say that I opened the project group OrpheusDelphi.groupproj in the IDE, built all packages and installed them without issue.

**Comment by flydev-fr** [comment]
Ok thanks you, your comment make found the issue. It was my environment variable `path` that was "broken".
