### ISSUE TITLE
Installation fails on CBuilder Alexandria

### ISSUE THREAD

**Issue by JEChristie** [TurboPack/Orpheus#29]
Install using Getit Package Manager fails linking OrpheusCD280

Installing manually OrpheusDBCR280, OrpheusDBCD280 and OrpheusCD280 all compile & link but OrpheusCR280 fails to link with:
[ilink32 Error] Error: Unresolved external '__InitVCL' referenced from C:\PROGRAM FILES (X86)\EMBARCADERO\STUDIO\21.0\LIB\WIN32\RELEASE\CP32MTI.LIB|crtlvcl
[ilink32 Error] Error: Unresolved external '__ExitVCL' referenced from C:\PROGRAM FILES (X86)\EMBARCADERO\STUDIO\21.0\LIB\WIN32\RELEASE\CP32MTI.LIB|crtlvcl

**Comment by romankassebaum** [comment]
I just checked and I can compile all packages with C++Builder in Alexandria.  I used the latest version from GitHub. I'm absolutely no C++ specialist, but maybe you have a problem with different versions of RAD Studio, since I see the "21.0" in your paths.

**Comment by JEChristie** [comment]
Uninstalled, manually deleted some directories, reinstalled via Getit and it worked.
