### ISSUE TITLE
64Bit-issue in ovceditp.pas

### ISSUE THREAD

**Issue by Armin-Biernaczyk** [TurboPack/Orpheus#35]
In the function TOvcUndoBuffer.NthRec, the cast to 'Cardinal' must be replaced by 'NativeUInt':

function TOvcUndoBuffer.NthRec(N : Integer) : PUndoRec; register;
...
begin
  result := PUndoRec(self.Buffer);
  while N>1 do begin
    result := PUndoRec(**Cardinal**(result) + UndoRecSize + result^.DSize*SizeOf(Char));
    Dec(N);
  end;
end;

**Comment by romankassebaum** [comment]
Fixed.
