### ISSUE TITLE
can't install design time components

### ISSUE THREAD

**Issue by gorpro** [TurboPack/Orpheus#4]
hello

when I try to install design time components an error occures:

Registration procedure, Ovcregdb.register in package c:\users\public\documents\embarcadero\studio\17.0\BPL\OrpheusDBCD240.bpl  raised exception class EAccessViolation: Access violation at address 50067AF1 in module 'rtl230.bpl'. Read of address 90900002.

can you please help me to resolve this issue.

best regards,
goran

**Comment by romankassebaum** [comment]
I think that you are mixing 10.0 Seattle (suffix 230) and 10.1 Berlin (suffix 240). You can find the Orpheus lib for Seattle here: https://github.com/TurboPack-Seattle/Orpheus

**Comment by gorpro** [comment]
hello roman,

thank you for help. 

you are right about mixing versions. now a downloaded the correct version, but again can't install OrpheusDBCD230.bpl package. the error is the same:

Registration procedure, Ovcregdb.register in package c:\users\public\documents\embarcadero\studio\17.0\BPL\OrpheusDBCD230.bpl raised exception class EAccessViolation: Access violation at address 50067AF1 in module 'rtl230.bpl'. Read of address 90900002.

**Comment by romankassebaum** [comment]
I just installed Orpheus into Seattle without problems. 

Please check that there are no old Orpheus bpl on your machine and try to reinstall the new ones.
