### ISSUE TITLE
Issue with Anchors moving components off the screen

### ISSUE THREAD

**Issue by tranquilodn** [TurboPack/Orpheus#41]
Hi!

I've reported an issue few weeks ago regarding using anchors.

There was a missing bit on the file I sent you last time. I'm adding the file with the missing bit.

Thank you so much.

Kind regards,

Tranquilo.
[ovcnbk.zip](https://github.com/TurboPack/Orpheus/files/11146519/ovcnbk.zip)

**Comment by romankassebaum** [comment]
I added this fix. Many thanks.
