### ISSUE TITLE
Access Violation on Paste (64-bit)

### ISSUE THREAD

**Issue by jbhickey** [TurboPack/Orpheus#43]
Tested ctrl-c + ctrl-v of plain text into picture field caused access violation on PastePrim accessing PChar(Msg.lParam)

Fix by changing:
TMessage(Msg).lParam := Integer(GlobalLock(H)); -> TMessage(Msg).lParam := **LPARAM**(GlobalLock(H));

in "**source/OvcEF.pas**": TOvcBaseEntryField.WMPaste

**Comment by romankassebaum** [comment]
Fixed.
Many thanks.
