### ISSUE TITLE
Orpheus will not install from within 10.1 Berlin

### ISSUE THREAD

**Issue by Trasd** [TurboPack/Orpheus#9]
Orpheus' compiling and installation fail when using the IDE's **Get Add-ons from GetIt** in 10.1 Berlin (64bit Starter).

It looks like all packages compile correctly until it gets to **OrpheusDBCD**.  I've tried the installation a number of times.  My Embarcadero C++Builder is not installed to the default directory.

Dialog box: 
![orpheuserror](https://cloud.githubusercontent.com/assets/2529883/17087657/19c1750a-51d5-11e6-91b9-84895450407b.png)

**Comment by marcocantu** [comment]
Seems starter edition lacks some of the required DB components. We could disable Starter from GetIt, or create a partial package for this release -- not sure what would make more sense.

**Comment by Trasd** [comment]
I think adding database capabilities back to the Starter editions would make more sense than anything!  After all, the $250 price tag is a lot for a severely crippled version.

Over the years, more and more has been removed from affordable solutions for the hobbyist - the geniuses of Turbo C's success.  I may just dig out my Builder 4 Pro again (Embarcadero C++Builder Starter limits me to 32 bit, anyway).  I have the original Turbo C (and books) dating back to the dawn of Borland.  I feel like my hands are tied with Embarcadero, though.  I fail to understand the allure, anymore.  More has been removed than added.  Is there any wonder Embarcadero is sinking in the market?

Baring that, I think the offending components should be removed from the package (a poor-man's version, if you will).  Data-aware components was the reason I stuck with this compiler; remove that and I have to find my solutions elsewhere.  Honestly, I think I'll check out M$'s Community eddition or an open source project.  I'm so tired of fighting with Embarcdero, who never listens anyway.

Come to think of it, I'd probably be better served to uninstall Berlin altogether.  I'm not sure Embarcadero will include a compiler in their next version, without dropping a few thousand bucks for an upgrade eddition.

**Comment by romankassebaum** [comment]
Could you please try to install the latest version from GitHub instead the GetIt version? Maybe this helps.

**Comment by Trasd** [comment]
Thank you, Roman, but unfortunately, there are still fatal errors.

I won't pretend to be an expert in creating or compiling bpls, in fact, I haven't messed with creating VCLs since CBuilder 4 (or maybe 6), mostly because I know C, not Pascal!  Also, in this case, the directions in the readme.txt file are lacking and, in some places, just wrong.  Given all this, I'm fairly confident I did the build correctly.

Everything does seem to compile (with a number of warnings), but will not link.  I think it is the Personal version's continued stripping of libraries that is the culprit, again.

Now, I'm getting the following fatal error:

[ilink32 Error] Fatal: Unable to open file 'VCLDBX.BPI'

Thanks.

**Comment by romankassebaum** [comment]
Could you please try only to compile and install the OrpheusCR and OrpheusCD packages? 

If this works please try to find a VCLDBX.* on your machine.

**Comment by Trasd** [comment]
@romankassebaum  I'm must apologize as I'm in the process of a job transfer to another state.  The computer isn't packed yet, but I don't know when (or if) I'll get a chance to try your suggestion anytime soon.

Can you can please keep the ticket open, unless, of course, someone else takes over?

Thanks.

**Comment by Trasd** [comment]
Believe it or not, I'm still not moved!  If possible, I would like for you to keep the ticket opened.

As soon as I'm in and settled, I'll get to it - probably another month, at least.

Thanks for your patience....

**Comment by Trasd** [comment]
romankassebaum, that didn't take long.

Orpheus compiled and installed fine (from within the IDE) after I installed Berlin Update 1.  Unfortunately, it will be a bit until I can test it.

I would say to go ahead and close the ticket for now and if I run into problems when I finally get a chance to testing it, I will open another.

Thanks.
